on:
  workflow_dispatch:
  push:
    # branches:
      # - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

name: Checkout and Create Release Version

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [trustauth, wotrus]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tag
        id: get_tag
        run: |
            TAG=$(basename ${GITHUB_REF})
            echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{matrix.component}}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository_owner }}/${{matrix.component}}_nginx:${{ steps.get_tag.outputs.TAG }}
            ${{ github.repository_owner }}/${{matrix.component}}_nginx:latest
            ghcr.io/${{ github.repository_owner }}/${{matrix.component}}_nginx:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/${{ github.repository_owner }}/${{matrix.component}}_nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-gmssl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [gmssl]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tag
        id: get_tag
        run: |
            TAG=$(basename ${GITHUB_REF})
            echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{matrix.component}}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository_owner }}/${{matrix.component}}_nginx:${{ steps.get_tag.outputs.TAG }}
            ${{ github.repository_owner }}/${{matrix.component}}_nginx:latest
            ghcr.io/${{ github.repository_owner }}/${{matrix.component}}_nginx:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/${{ github.repository_owner }}/${{matrix.component}}_nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max